name: CI
on:
  pull_request:
    branches: [develop, staging, release, main]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          cache: true
      - run: flutter pub get
      - run: flutter analyze --fatal-infos
      - run: flutter test